	.Z80

	.xlist
	include	$SYSFN.INC
	include	$QIO.INC
	.list

CR	equ	0Dh
LF	equ	0Ah

;-----------------------------------------------------------------------

; "Hello world" example using direct QIO calls.

	cseg

HELLO::	ld	sp,stack
	ld	hl,qio1
	SC	.QIO
	ld	hl,0
	SC	.EXIT

qio1:	QIOW$	IO.WVB,5,1,iosb,,<str,len,' '>
str:	db	'Hello, world!'
len	equ	$-str

	dseg

iosb:	ds	4
	ds	64		; stack space
stack	equ	$

	end	HELLO
