	.Z80

	.xlist
	include	SYSFN.INC
	include	QIO.INC
	.list

CR	equ	0Dh
LF	equ	0Ah

; Program to test the typeahead feature of the terminal driver.

	cseg

QTEST::	ld	sp,stack
	ld	hl,qioatt
	SC	.QIO		; attach terminal
	ld	hl,qiowr
	SC	.QIO		; display prompt
	ld	hl,qiord
	SC	.QIO		; get a line from terminal
	ld	hl,3
	ld	d,2
	call	SLEEP##		; sleep for a few seconds. During this time
				;  anything you type should not get lost, but
				;   kept in the typeahead buffer instead
	ld	hl,qiowr
	SC	.QIO		; display prompt again
	ld	hl,qiord
	SC	.QIO		; get another line from terminal. Anything
				;  you typed while the task was paused should
				;   appear here before any new characters are
				;    typed.
	ld	hl,0
	SC	.EXIT		; exit

qioatt:	QIOW$	IO.ATT,5,1,iosb,,<>
qiord:	QIOW$	IO.RVB,5,1,iosb,,<buf,10,,0,0,>
qiowr:	QIOW$	IO.WVB,5,1,iosb,,<str,len,'$'>

str:	db	'Type something: '
len	equ	$-str

	dseg

buf:	ds	10
iosb:	ds	4
	ds	64		; stack space
stack	equ	$

	end	QTEST
