ins $fdisk
ins $fmt
ins $bad
ins $vfy
ins $clock
ins [test]ds1820/task=...tem
ins [test]bcdtest/task=...rpn
ins [games]xonix
ins [games]pacman
ins [games]tetris
ins [games]snake
ins [games]volcano
ins [games]spcinv
