; Codes for the supported serial baud rates

S.0	equ	0	; Baud rates not supported
S.50	equ	1
S.75	equ	2
S.110	equ	3
S.134	equ	4	; IBM Selectric typewriter
S.150	equ	5
S.200	equ	6
S.300	equ	7
S.600	equ	8
S.1200	equ	9
S.1800	equ	10
S.2000	equ	11
S.2400	equ	12
S.3600	equ	13
S.4800	equ	14
S.7200	equ	15
S.9600	equ	16
S.14K4	equ	17
S.19K2	equ	18
S.28K8	equ	19
S.38K4	equ	20
S.57K6	equ	21
S.76K8	equ	22
S.115K2	equ	23
S.UNK	equ	-1	; Unknown

